version: "3.7"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.local
    env_file:
      - ./.env
    command: "uvicorn main:app --host 0.0.0.0 --port ${PORT} --reload"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /code/k.json
      service_account: ${service_account}
    volumes:
      - .:/code
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/code/k.json:ro
    ports:
      - "${PORT}:${PORT}"


